name: Actions Smoke Test

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths:
      - ".github/workflows/actions-smoke-test.yml"

permissions:
  contents: read

jobs:
  hello:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Say hello
        run: echo "GitHub Actions runner is working"
